/*
 * @Date: 2024-08-06 16:19:59
 * @FilePath: /AS-WEB-3.5/src/core/templates/mobile-horizontal/pages/kyc/information/const.ts
 * @Description:
 */
import _ from 'lodash'
import type { TFieldProps } from './types'

export const fields: Array<TFieldProps> = [
  { name: $t('国籍'), field: 'nationality', position: 'left' },
  { name: $t('生日'), field: 'birthday', position: 'left' },
  { name: $t('职业'), field: 'work', position: 'left' },
  { name: $t('出生地'), field: 'birth_place', position: 'left' },
  { name: $t('户籍地'), field: 'permanent_address', position: 'left' },
  { name: $t('姓名'), field: 'full_name', position: 'right' },
  { name: $t('性别'), field: 'gender', position: 'right' },
  { name: $t('收入来源'), field: 'income_source', position: 'right' },
  { name: $t('联络地址'), field: 'current_address', position: 'right' },
]

// 职业
export const workOptions = _.uniqBy(
  [
    { value: '', label: 'Please select' },
    { value: 'Assistant', label: 'Assistant' },
    { value: 'Associate', label: 'Associate' },
    { value: 'Account Manager', label: 'Account Manager' },
    { value: 'Assistant Manager', label: 'Assistant Manager' },
    { value: 'Accountant', label: 'Accountant' },
    { value: 'Analyst', label: 'Analyst' },
    { value: 'Administrative Clerk', label: 'Administrative Clerk' },
    { value: 'Administrative Aide', label: 'Administrative Aide' },
    { value: 'Administration Assistant', label: 'Administration Assistant' },
    { value: 'Account Executive', label: 'Account Executive' },
    { value: 'Business Owner', label: 'Business Owner' },
    { value: 'Business Specialist', label: 'Business Specialist' },
    { value: 'Business Manager', label: 'Business Manager' },
    { value: 'Business Analyst', label: 'Business Analyst' },
    { value: 'Business Professional', label: 'Business Professional' },
    {
      value: 'Business Development Specialist',
      label: 'Business Development Specialist',
    },
    { value: 'Branch Manager', label: 'Branch Manager' },
    { value: 'Book Keeper', label: 'Book Keeper' },
    {
      value: 'Biomedical Equipment Technician',
      label: 'Biomedical Equipment Technician',
    },
    { value: 'Company Owner', label: 'Company Owner' },
    { value: 'Consultant', label: 'Consultant' },
    { value: 'Chief Executive Officer', label: 'Chief Executive Officer' },
    { value: 'Computer Programmer', label: 'Computer Programmer' },
    {
      value: 'Customer Service Representative',
      label: 'Customer Service Representative',
    },
    { value: 'Chief Executive', label: 'Chief Executive' },
    { value: 'Cashier', label: 'Cashier' },
    { value: 'Carpenter', label: 'Carpenter' },
    { value: 'Communication Specialist', label: 'Communication Specialist' },
    { value: 'Child Care Specialist', label: 'Child Care Specialist' },
    { value: 'Computer Programmer', label: 'Computer Programmer' },
    { value: 'Construction Worker', label: 'Construction Worker' },
    { value: 'Developer', label: 'Developer' },
    { value: 'Director', label: 'Director' },
    { value: 'Driver', label: 'Driver' },
    { value: 'Disk Jockey', label: 'Disk Jockey' },
    { value: 'Data Analyst', label: 'Data Analyst' },
    { value: 'Delivery Driver', label: 'Delivery Driver' },
    { value: 'Dance Instructor', label: 'Dance Instructor' },
    { value: 'Learning Facilitator', label: 'Learning Facilitator' },
    { value: 'Law Clerk', label: 'Law Clerk' },
    { value: 'Lecturer', label: 'Lecturer' },
    { value: 'Lead', label: 'Lead' },
    { value: 'Logistics Specialist', label: 'Logistics Specialist' },
    { value: 'Laboratory Specialist', label: 'Laboratory Specialist' },
    { value: 'Laborer', label: 'Laborer' },
    { value: 'Engineer', label: 'Engineer' },
    { value: 'Employer', label: 'Employer' },
    { value: 'Executive', label: 'Executive' },
    { value: 'Educator', label: 'Educator' },
    { value: 'Engineer', label: 'Engineer' },
    { value: 'Executive Assistant', label: 'Executive Assistant' },
    { value: 'Economist', label: 'Economist' },
    { value: 'Editor', label: 'Editor' },
    { value: 'Electrician', label: 'Electrician' },
    { value: 'Employee', label: 'Employee' },
    { value: 'Founder', label: 'Founder' },
    { value: 'Fresher', label: 'Fresher' },
    { value: 'Co-Founder', label: 'Co-Founder' },
    { value: 'Finance Specialist', label: 'Finance Specialist' },
    { value: 'Field Specialist', label: 'Field Specialist' },
    { value: 'Finance Manager', label: 'Finance Manager' },
    { value: 'Financial Analyst', label: 'Financial Analyst' },
    { value: 'Financial Advisor', label: 'Financial Advisor' },
    { value: 'Food Server', label: 'Food Server' },
    { value: 'General Manager', label: 'General Manager' },
    { value: 'Graphic Designer', label: 'Graphic Designer' },
    { value: 'General', label: 'General' },
    { value: 'Graduate', label: 'Graduate' },
    { value: 'General Member Board', label: 'General Member Board' },
    { value: 'Human Resource Specialist', label: 'Human Resource Specialist' },
    { value: 'Head', label: 'Head' },
    { value: 'Human Resource Manager', label: 'Human Resource Manager' },
    { value: 'Homemaker', label: 'Homemaker' },
    { value: 'Host', label: 'Host' },
    { value: 'Human Resource Supervisor', label: 'Human Resource Supervisor' },
    { value: 'Human Resource Assistant', label: 'Human Resource Assistant' },
    { value: 'Housekeeping Staff', label: 'Housekeeping Staff' },
    { value: 'Instructor', label: 'Instructor' },
    { value: 'Intern', label: 'Intern' },
    {
      value: 'Information Technology Specialist',
      label: 'Information Technology Specialist',
    },
    {
      value: 'Internet Network Specialist',
      label: 'Internet Network Specialist',
    },
    { value: 'Kitchen Staff', label: 'Kitchen Staff' },
    { value: 'Keyholder', label: 'Keyholder' },
    { value: 'Kitchen Manager', label: 'Kitchen Manager' },
    { value: 'Journalist', label: 'Journalist' },
    { value: 'Research Assistant', label: 'Research Assistant' },
    { value: 'Research Fellow', label: 'Research Fellow' },
    { value: 'Retired', label: 'Retired' },
    { value: 'Researcher', label: 'Researcher' },
    { value: 'Receptionist', label: 'Receptionist' },
    { value: 'Relationship Manager', label: 'Relationship Manager' },
    { value: 'Representative', label: 'Representative' },
    {
      value: 'Quality Assurance Specialist',
      label: 'Quality Assurance Specialist',
    },
    { value: 'Quality Assurance Manager', label: 'Quality Assurance Manager' },
    { value: 'QA Specialist', label: 'QA Specialist' },
    {
      value: 'Quality Assurance Engineer',
      label: 'Quality Assurance Engineer',
    },
    { value: 'Quality Assurance Analyst', label: 'Quality Assurance Analyst' },
    { value: 'Quantity Surveyor', label: 'Quantity Surveyor' },
    { value: 'Project Manager', label: 'Project Manager' },
    { value: 'Project Expert', label: 'Project Expert' },
    { value: 'Program Coordinator', label: 'Program Coordinator' },
    { value: 'Proprietor', label: 'Proprietor' },
    { value: 'Programmer', label: 'Programmer' },
    { value: 'Professional Singer', label: 'Professional Singer' },
    { value: 'Office Manager', label: 'Office Manager' },
    { value: 'Owner', label: 'Owner' },
    { value: 'Office Associate', label: 'Office Associate' },
    { value: 'Office Helper', label: 'Office Helper' },
    { value: 'Officer Incharge', label: 'Officer Incharge' },
    { value: 'Organizational Manager', label: 'Organizational Manager' },
    { value: 'Operational Specialist', label: 'Operational Specialist' },
    { value: 'Observer', label: 'Observer' },
    { value: 'Operations Manager', label: 'Operations Manager' },
    { value: 'Nurse', label: 'Nurse' },
    { value: 'Nursing Assistant', label: 'Nursing Assistant' },
    { value: 'Network Engineer', label: 'Network Engineer' },
    { value: 'Network Administrator', label: 'Network Administrator' },
    { value: 'Network Professional', label: 'Network Professional' },
    { value: 'Network Expert', label: 'Network Expert' },
    {
      value: 'National Account Specialist',
      label: 'National Account Specialist',
    },
    { value: 'Manager', label: 'Manager' },
    { value: 'Managing Director', label: 'Managing Director' },
    { value: 'Management Executive', label: 'Management Executive' },
    { value: 'Management Staff', label: 'Management Staff' },
    { value: 'Marketing Specialist', label: 'Marketing Specialist' },
    { value: 'Technician', label: 'Technician' },
    { value: 'Team Lead', label: 'Team Lead' },
    { value: 'Teaching Professional', label: 'Teaching Professional' },
    { value: 'Sales Attendant', label: 'Sales Attendant' },
    { value: 'Sales Associate', label: 'Sales Associate' },
    { value: 'Salesperson', label: 'Salesperson' },
    { value: 'Sales Specialist', label: 'Sales Specialist' },
    {
      value: 'Sales and Marketing Specialist',
      label: 'Sales and Marketing Specialist',
    },
    { value: 'Software Engineer', label: 'Software Engineer' },
    { value: 'Senior Software Engineer', label: 'Senior Software Engineer' },
    { value: 'Supervisor', label: 'Supervisor' },
    { value: 'Sales Division', label: 'Sales Division' },
    { value: 'Sales Department', label: 'Sales Department' },
    { value: 'Secretary', label: 'Secretary' },
    { value: 'Self Employed', label: 'Self Employed' },
    { value: 'Scientific Researcher', label: 'Scientific Researcher' },
    { value: 'Senior Underwriter', label: 'Senior Underwriter' },
    { value: 'Security Guard', label: 'Security Guard' },
    { value: 'Seller', label: 'Seller' },
    { value: 'Unemployed', label: 'Unemployed' },
    { value: 'Underwriter', label: 'Underwriter' },
    { value: 'Utilities Specialist', label: 'Utilities Specialist' },
    { value: 'UX Designer', label: 'UX Designer' },
    { value: 'UI Designer', label: 'UI Designer' },
    { value: 'Undergraduate', label: 'Undergraduate' },
    {
      value: 'Undergraduate Research Fellow',
      label: 'Undergraduate Research Fellow',
    },
    { value: 'Volunteer', label: 'Volunteer' },
    { value: 'Virtual Assistant', label: 'Virtual Assistant' },
    { value: 'Vendor', label: 'Vendor' },
    { value: 'Worker', label: 'Worker' },
    { value: 'Writer', label: 'Writer' },
    { value: 'Web Developer', label: 'Web Developer' },
    { value: 'Waiter', label: 'Waiter' },
    { value: 'Waitress', label: 'Waitress' },
    { value: 'X-Ray Technician', label: 'X-Ray Technician' },
    { value: 'Youth Specialist', label: 'Youth Specialist' },
    { value: 'Youth Worker', label: 'Youth Worker' },
    { value: 'Youth Director', label: 'Youth Director' },
    { value: 'Youth Development', label: 'Youth Development' },
    { value: 'Youth Pastor', label: 'Youth Pastor' },
    { value: 'Youth Coordinator', label: 'Youth Coordinator' },
    { value: 'Youth Counselor', label: 'Youth Counselor' },
    { value: 'Youth Lead', label: 'Youth Lead' },
    { value: 'Youth Minister', label: 'Youth Minister' },
    { value: 'Yoga Instructor', label: 'Yoga Instructor' },
    { value: 'Zone Manager', label: 'Zone Manager' },
    { value: 'Zoologist', label: 'Zoologist' },
  ],
  'value',
)

// 收入来源
export const incomeSourceOptions = [
  { value: '', label: 'Please select' },
  { value: 'Salary', label: $t('薪资') },
  { value: 'Income From Own Business', label: $t('自营收入') },
  { value: 'Savings', label: $t('储蓄') },
  { value: 'Investment', label: $t('投资') },
  { value: 'Self-employed', label: $t('自由职业') },
  { value: 'Others', label: $t('其他') },
]

// 性别
export const genderOptions = [
  { value: '1', label: $t('男') },
  { value: '0', label: $t('女') },
  { value: '2', label: $t('其他') },
]

// 身份证类型
export const idTypeOptions = [
  { value: '1', label: "Driver's License" },
  { value: '2', label: 'ID Passport (Philippine/Foreign)' },
  { value: '3', label: 'Social Security System (SSS) Card' },
  { value: '4', label: 'Tax Identification (TIN)' },
  { value: '5', label: 'Unified Multi-Purpose ID (UMID)' },
  { value: '6', label: "Voter's Certificate" },
  { value: '7', label: 'Valid Passport' },
  { value: '8', label: 'PhilHealth ID' },
  { value: '9', label: 'Postal ID' },
  { value: '10', label: 'NBI Clearance' },
  { value: '11', label: 'Senior Citizen Card' },
  { value: '12', label: 'Overseas Workers Welfare Administration (OWWA)' },
  { value: '13', label: 'Firearms License' },
  { value: '14', label: 'Police Clearance' },
  { value: '15', label: 'Integrated Bar of the Philippines ID' },
  { value: '16', label: "Seaman's Book" },
  { value: '17', label: 'Professional Regulations Commission' },
  { value: '18', label: 'Overseas Filipino Workers (OFW) ID' },
  { value: '19', label: 'Maritime Industry Authority (MARINA) ID' },
  { value: '20', label: 'Philippine National ID' },
  { value: '21', label: 'Alien Certificate of Registration' },
  { value: '22', label: 'Immigrant Certificate of Registration' },
  { value: '23', label: 'National ID' },
  { value: '24', label: 'Other' },
]
