// 国籍
export const nationalityOptions = [
  { value: 'Philippines', label: $t('菲律宾') },
  { value: 'Afghanistan', label: $t('阿富汗') },
  { value: 'Albania', label: $t('阿尔巴尼亚') },
  { value: 'Algeria', label: $t('阿尔及利亚') },
  { value: 'Andorra', label: $t('安道尔') },
  { value: 'Angola', label: $t('安哥拉') },
  { value: 'Argentina', label: $t('阿根廷') },
  { value: 'Armenia', label: $t('亚美尼亚') },
  { value: 'Australia', label: $t('澳大利亚') },
  { value: 'Austria', label: $t('奥地利') },
  { value: 'Azerbaijan', label: $t('阿塞拜疆') },
  { value: 'Bahamas', label: $t('巴哈马') },
  { value: 'Bahrain', label: $t('巴林') },
  { value: 'Bangladesh', label: $t('孟加拉国') },
  { value: 'Barbados', label: $t('巴巴多斯') },
  { value: 'Belarus', label: $t('白俄罗斯') },
  { value: 'Belgium', label: $t('比利时') },
  { value: 'Belize', label: $t('伯利兹') },
  { value: 'Benin', label: $t('贝宁') },
  { value: 'Bhutan', label: $t('不丹') },
  { value: 'Bolivia', label: $t('玻利维亚') },
  { value: 'Bosnia and Herzegovina', label: $t('波斯尼亚和黑塞哥维那') },
  { value: 'Botswana', label: $t('博茨瓦纳') },
  { value: 'Brazil', label: $t('巴西') },
  { value: 'Brunei', label: $t('文莱') },
  { value: 'Bulgaria', label: $t('保加利亚') },
  { value: 'Burkina Faso', label: $t('布基纳法索') },
  { value: 'Burundi', label: $t('布隆迪') },
  { value: 'Cambodia', label: $t('柬埔寨') },
  { value: 'Cameroon', label: $t('喀麦隆') },
  { value: 'Canada', label: $t('加拿大') },
  { value: 'Cape Verde', label: $t('佛得角') },
  { value: 'Central African Republic', label: $t('中非共和国') },
  { value: 'Chad', label: $t('乍得') },
  { value: 'Chile', label: $t('智利') },
  { value: 'China', label: $t('中国') },
  { value: 'Colombia', label: $t('哥伦比亚') },
  { value: 'Comoros', label: $t('科摩罗') },
  { value: 'Congo', label: $t('刚果') },
  { value: 'Costa Rica', label: $t('哥斯达黎加') },
  { value: 'Croatia', label: $t('克罗地亚') },
  { value: 'Cuba', label: $t('古巴') },
  { value: 'Cyprus', label: $t('塞浦路斯') },
  { value: 'Czech Republic', label: $t('捷克共和国') },
  { value: 'Denmark', label: $t('丹麦') },
  { value: 'Djibouti', label: $t('吉布提') },
  { value: 'Dominica', label: $t('多米尼加') },
  { value: 'Dominican Republic', label: $t('多米尼加共和国') },
  { value: 'East Timor', label: $t('东帝汶') },
  { value: 'Ecuador', label: $t('厄瓜多尔') },
  { value: 'Egypt', label: $t('埃及') },
  { value: 'El Salvador', label: $t('萨尔瓦多') },
  { value: 'Equatorial Guinea', label: $t('赤道几内亚') },
  { value: 'Eritrea', label: $t('厄立特里亚') },
  { value: 'Estonia', label: $t('爱沙尼亚') },
  { value: 'Eswatini', label: $t('斯威士兰') },
  { value: 'Ethiopia', label: $t('埃塞俄比亚') },
  { value: 'Fiji', label: $t('斐济') },
  { value: 'Finland', label: $t('芬兰') },
  { value: 'France', label: $t('法国') },
  { value: 'Gabon', label: $t('加蓬') },
  { value: 'Gambia', label: $t('冈比亚') },
  { value: 'Georgia', label: $t('格鲁吉亚') },
  { value: 'Germany', label: $t('德国') },
  { value: 'Ghana', label: $t('加纳') },
  { value: 'Greece', label: $t('希腊') },
  { value: 'Grenada', label: $t('格林纳达') },
  { value: 'Guatemala', label: $t('危地马拉') },
  { value: 'Guinea', label: $t('几内亚') },
  { value: 'Guinea-Bissau', label: $t('几内亚比绍') },
  { value: 'Guyana', label: $t('圭亚那') },
  { value: 'Haiti', label: $t('海地') },
  { value: 'Honduras', label: $t('洪都拉斯') },
  { value: 'Hungary', label: $t('匈牙利') },
  { value: 'Iceland', label: $t('冰岛') },
  { value: 'India', label: $t('印度') },
  { value: 'Indonesia', label: $t('印度尼西亚') },
  { value: 'Iran', label: $t('伊朗') },
  { value: 'Iraq', label: $t('伊拉克') },
  { value: 'Ireland', label: $t('爱尔兰') },
  { value: 'Israel', label: $t('以色列') },
  { value: 'Italy', label: $t('意大利') },
  { value: 'Jamaica', label: $t('牙买加') },
  { value: 'Japan', label: $t('日本') },
  { value: 'Jordan', label: $t('约旦') },
  { value: 'Kazakhstan', label: $t('哈萨克斯坦') },
  { value: 'Kenya', label: $t('肯尼亚') },
  { value: 'Kiribati', label: $t('基里巴斯') },
  { value: 'Kuwait', label: $t('科威特') },
  { value: 'Kyrgyzstan', label: $t('吉尔吉斯斯坦') },
  { value: 'Laos', label: $t('老挝') },
  { value: 'Latvia', label: $t('拉脱维亚') },
  { value: 'Lebanon', label: $t('黎巴嫩') },
  { value: 'Lesotho', label: $t('莱索托') },
  { value: 'Liberia', label: $t('利比里亚') },
  { value: 'Libya', label: $t('利比亚') },
  { value: 'Liechtenstein', label: $t('列支敦士登') },
  { value: 'Lithuania', label: $t('立陶宛') },
  { value: 'Luxembourg', label: $t('卢森堡') },
  { value: 'Madagascar', label: $t('马达加斯加') },
  { value: 'Malawi', label: $t('马拉维') },
  { value: 'Malaysia', label: $t('马来西亚') },
  { value: 'Maldives', label: $t('马尔代夫') },
  { value: 'Mali', label: $t('马里') },
  { value: 'Malta', label: $t('马耳他') },
  { value: 'Marshall Islands', label: $t('马绍尔群岛') },
  { value: 'Mauritania', label: $t('毛里塔尼亚') },
  { value: 'Mauritius', label: $t('毛里求斯') },
  { value: 'Mexico', label: $t('墨西哥') },
  { value: 'Micronesia', label: $t('密克罗尼西亚') },
  { value: 'Moldova', label: $t('摩尔多瓦') },
  { value: 'Monaco', label: $t('摩纳哥') },
  { value: 'Mongolia', label: $t('蒙古') },
  { value: 'Montenegro', label: $t('黑山') },
  { value: 'Morocco', label: $t('摩洛哥') },
  { value: 'Mozambique', label: $t('莫桑比克') },
  { value: 'Myanmar', label: $t('缅甸') },
  { value: 'Namibia', label: $t('纳米比亚') },
  { value: 'Nauru', label: $t('瑙鲁') },
  { value: 'Nepal', label: $t('尼泊尔') },
  { value: 'Netherlands', label: $t('荷兰') },
  { value: 'New Zealand', label: $t('新西兰') },
  { value: 'Nicaragua', label: $t('尼加拉瓜') },
  { value: 'Niger', label: $t('尼日尔') },
  { value: 'Nigeria', label: $t('尼日利亚') },
  { value: 'North Korea', label: $t('朝鲜') },
  { value: 'North Macedonia', label: $t('北马其顿') },
  { value: 'Norway', label: $t('挪威') },
  { value: 'Oman', label: $t('阿曼') },
  { value: 'Pakistan', label: $t('巴基斯坦') },
  { value: 'Palau', label: $t('帕劳') },
  { value: 'Panama', label: $t('巴拿马') },
  { value: 'Papua New Guinea', label: $t('巴布亚新几内亚') },
  { value: 'Paraguay', label: $t('巴拉圭') },
  { value: 'Peru', label: $t('秘鲁') },
  { value: 'Poland', label: $t('波兰') },
  { value: 'Portugal', label: $t('葡萄牙') },
  { value: 'Qatar', label: $t('卡塔尔') },
  { value: 'Romania', label: $t('罗马尼亚') },
  { value: 'Russia', label: $t('俄罗斯') },
  { value: 'Rwanda', label: $t('卢旺达') },
  { value: 'Saint Kitts and Nevis', label: $t('圣基茨和尼维斯') },
  { value: 'Saint Lucia', label: $t('圣卢西亚') },
  {
    value: 'Saint Vincent and the Grenadines',
    label: $t('圣文森特和格林纳丁斯'),
  },
  { value: 'Samoa', label: $t('萨摩亚') },
  { value: 'San Marino', label: $t('圣马力诺') },
  { value: 'Sao Tome and Principe', label: $t('圣多美和普林西比') },
  { value: 'Saudi Arabia', label: $t('沙特阿拉伯') },
  { value: 'Senegal', label: $t('塞内加尔') },
  { value: 'Serbia', label: $t('塞尔维亚') },
  { value: 'Seychelles', label: $t('塞舌尔') },
  { value: 'Sierra Leone', label: $t('塞拉利昂') },
  { value: 'Singapore', label: $t('新加坡') },
  { value: 'Slovakia', label: $t('斯洛伐克') },
  { value: 'Slovenia', label: $t('斯洛文尼亚') },
  { value: 'Solomon Islands', label: $t('所罗门群岛') },
  { value: 'Somalia', label: $t('索马里') },
  { value: 'South Africa', label: $t('南非') },
  { value: 'South Korea', label: $t('韩国') },
  { value: 'South Sudan', label: $t('南苏丹') },
  { value: 'Spain', label: $t('西班牙') },
  { value: 'Sri Lanka', label: $t('斯里兰卡') },
  { value: 'Sudan', label: $t('苏丹') },
  { value: 'Suriname', label: $t('苏里南') },
  { value: 'Sweden', label: $t('瑞典') },
  { value: 'Switzerland', label: $t('瑞士') },
  { value: 'Syria', label: $t('叙利亚') },
  { value: 'Taiwan', label: $t('台湾') },
  { value: 'Tajikistan', label: $t('塔吉克斯坦') },
  { value: 'Tanzania', label: $t('坦桑尼亚') },
  { value: 'Thailand', label: $t('泰国') },
  { value: 'Togo', label: $t('多哥') },
  { value: 'Tonga', label: $t('汤加') },
  { value: 'Trinidad and Tobago', label: $t('特立尼达和多巴哥') },
  { value: 'Tunisia', label: $t('突尼斯') },
  { value: 'Turkey', label: $t('土耳其') },
  { value: 'Turkmenistan', label: $t('土库曼斯坦') },
  { value: 'Tuvalu', label: $t('图瓦卢') },
  { value: 'Uganda', label: $t('乌干达') },
  { value: 'Ukraine', label: $t('乌克兰') },
  { value: 'United Arab Emirates', label: $t('阿联酋') },
  { value: 'United Kingdom', label: $t('英国') },
  { value: 'United States', label: $t('美国') },
  { value: 'Uruguay', label: $t('乌拉圭') },
  { value: 'Uzbekistan', label: $t('乌兹别克斯坦') },
  { value: 'Vanuatu', label: $t('瓦努阿图') },
  { value: 'Vatican City', label: $t('梵蒂冈') },
  { value: 'Venezuela', label: $t('委内瑞拉') },
  { value: 'Vietnam', label: $t('越南') },
  { value: 'Yemen', label: $t('也门') },
  { value: 'Zambia', label: $t('赞比亚') },
  { value: 'Zimbabwe', label: $t('津巴布韦') },
]
